### ISSUE TITLE
jupyter-lab runtime path

### ISSUE THREAD

**Issue by djacu** [tweag/jupyter-nix#39]
#38 brings the `jupyter-lab` paths under nix's control by setting the `config`, `data`, and `runtime` paths to a place in the nix store. Specifically, setting the `runtime` path to an immutable location causes `jupyter-lab` to fail to start as it needs to write `jupyter_cookie_secret`, `jpserver-<pid>.json`, and `jpserver-<pid>-open.html` to the runtime directory. As these are ephemeral, it might be best and necessary to put these back in the default user directory. Unless, of course, there is a way to have a writable directory in the nix store.

```shell
$ ./result/bin/jupyter-lab
[I 2022-06-28 21:01:51.329 ServerApp] jupyterlab | extension was successfully linked.
[I 2022-06-28 21:01:51.335 ServerApp] Writing Jupyter server cookie secret to /nix/store/p6mjjls4iykvlb4incf08wy0rq579i4m-jupyter-dir/runtime/jupyter_cookie_secret
[E 2022-06-28 21:01:51.335 ServerApp] Failed to write cookie secret to /nix/store/p6mjjls4iykvlb4incf08wy0rq579i4m-jupyter-dir/runtime/jupyter_cookie_secret: [Errno 30] Read-only file system: '/nix/store/p6mjjls4iykvlb4incf08wy0rq579i4m-jupyter-dir/runtime/jupyter_cookie_secret'
[I 2022-06-28 21:01:51.345 LabApp] JupyterLab extension loaded from /nix/store/6sc285jv74aakjafwxgvcdx0yzsg9lhj-python3-3.10.4-env/lib/python3.10/site-packages/jupyterlab
[I 2022-06-28 21:01:51.346 LabApp] JupyterLab application directory is /nix/store/ywawa31mn9wma28h0dc84cf0b55zl5l4-python3.10-jupyterlab-3.4.3/share/jupyter/lab
[I 2022-06-28 21:01:51.348 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-06-28 21:01:51.349 ServerApp] Serving notebooks from local directory: /home/bakerdn/tweag/jupyter-nix
[I 2022-06-28 21:01:51.349 ServerApp] Jupyter Server 1.17.1 is running at:
[I 2022-06-28 21:01:51.349 ServerApp] http://localhost:8888/lab?token=aa2c3fddafa723ce466fce52d71e5412c5efa8d75970f5d1
[I 2022-06-28 21:01:51.349 ServerApp]  or http://127.0.0.1:8888/lab?token=aa2c3fddafa723ce466fce52d71e5412c5efa8d75970f5d1
[I 2022-06-28 21:01:51.349 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[E 2022-06-28 21:01:51.349 ServerApp] Failed to write server-info to /nix/store/p6mjjls4iykvlb4incf08wy0rq579i4m-jupyter-dir/runtime/jpserver-1778025.json: [Errno 30] Read-only file system: '/nix/store/p6mjjls4iykvlb4incf08wy0rq579i4m-jupyter-dir/runtime/jpserver-1778025.json'
Traceback (most recent call last):
  File "/nix/store/ywawa31mn9wma28h0dc84cf0b55zl5l4-python3.10-jupyterlab-3.4.3/bin/.jupyter-lab-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/6sc285jv74aakjafwxgvcdx0yzsg9lhj-python3-3.10.4-env/lib/python3.10/site-packages/jupyter_server/extension/application.py", line 594, in launch_instance
    serverapp.start()
  File "/nix/store/6sc285jv74aakjafwxgvcdx0yzsg9lhj-python3-3.10.4-env/lib/python3.10/site-packages/jupyter_server/serverapp.py", line 2814, in start
    self.start_app()
  File "/nix/store/6sc285jv74aakjafwxgvcdx0yzsg9lhj-python3-3.10.4-env/lib/python3.10/site-packages/jupyter_server/serverapp.py", line 2743, in start_app
    self.write_browser_open_files()
  File "/nix/store/6sc285jv74aakjafwxgvcdx0yzsg9lhj-python3-3.10.4-env/lib/python3.10/site-packages/jupyter_server/serverapp.py", line 2619, in write_browser_open_files
    self.write_browser_open_file()
  File "/nix/store/6sc285jv74aakjafwxgvcdx0yzsg9lhj-python3-3.10.4-env/lib/python3.10/site-packages/jupyter_server/serverapp.py", line 2642, in write_browser_open_file
    with open(self.browser_open_file, "w", encoding="utf-8") as f:
OSError: [Errno 30] Read-only file system: '/nix/store/p6mjjls4iykvlb4incf08wy0rq579i4m-jupyter-dir/runtime/jpserver-1778025-open.html'
```

**Comment by djacu** [comment]
To show the ephemeral nature of these files we can look at [_confirm_exit](https://github.com/jupyter-server/jupyter_server/blob/4f1e09e3ebf2bfd35441789986128077cc9cdf77/jupyter_server/serverapp.py#L2139) which calls [stop](https://github.com/jupyter-server/jupyter_server/blob/4f1e09e3ebf2bfd35441789986128077cc9cdf77/jupyter_server/serverapp.py#L2818) which calls [_stop](https://github.com/jupyter-server/jupyter_server/blob/4f1e09e3ebf2bfd35441789986128077cc9cdf77/jupyter_server/serverapp.py#L2812) which calls [_cleanup](https://github.com/jupyter-server/jupyter_server/blob/4f1e09e3ebf2bfd35441789986128077cc9cdf77/jupyter_server/serverapp.py#L2775). Within `_cleanup` are several functions that will clear out the runtime files as the server shuts down.

- [remove_server_info_file](https://github.com/jupyter-server/jupyter_server/blob/4f1e09e3ebf2bfd35441789986128077cc9cdf77/jupyter_server/serverapp.py#L2556) will remove the `jpserver-<pid>.json` file.
- [remove_browser_open_files](https://github.com/jupyter-server/jupyter_server/blob/4f1e09e3ebf2bfd35441789986128077cc9cdf77/jupyter_server/serverapp.py#L2639) will remove the `jpserver-<pid>-open.html` as well as a `jpserver-file-to-run-<pid>-open.html` file.
- It does not appear that `jupyter_cookie_secrets` gets removed as far as I can tell.

**Comment by djacu** [comment]
Also, even though the [documentation](https://docs.jupyter.org/en/latest/use/jupyter-directories.html#runtime-files) mentions using `XDG_RUNTIME_DIR` the code [docstring](https://github.com/jupyter/jupyter_core/blob/73401cc7c99c52822bc3f007652d67636297620d/jupyter_core/paths.py#L116) says it is no longer supported. Also, the variable is unset when building the flake file.
